# Week 1 CI: evidence-gate check + test suite (orchestration repo)
# Ensures evidence file exists and all Week 1 tests pass

name: Week 1 Evidence Gate

on:
  pull_request:
    paths:
      - 'aureus-openclaw-platform/**'

jobs:
  evidence-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Validate evidence file exists
        run: |
          if [ -f aureus-openclaw-platform/docs/evidence/week-01.md ]; then
            echo "Evidence present"
          else
            echo "Missing evidence file: please add aureus-openclaw-platform/docs/evidence/week-01.md" && exit 1
          fi

      - name: Schema tests
        run: node aureus-openclaw-platform/tests/schema-test-runner.js

      - name: Signer tests
        run: node aureus-openclaw-platform/tests/signer.test.js

      - name: Integration test
        run: node aureus-openclaw-platform/tests/integration.test.js

      - name: Executor wrapper test
        run: node aureus-openclaw-platform/tests/executor_wrapper.test.js

      - name: KMS adapter test (conditional)
        run: node aureus-openclaw-platform/tests/aws_kms_adapter.test.js
        continue-on-error: true  # Skips if TEST_KMS_KEY_ARN not set
