name: Build, Test, and Package

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  # Build stage
  build:
    name: Build All Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages in order
        run: npm run build:ordered

      - name: Build console app
        run: npm run build --workspace=@aureus/console

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            apps/console/dist/
            apps/console/src/ui/
            packages/*/dist/
          retention-days: 7

  # Test stage
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}

      - name: Run unit tests
        run: npm run test

      - name: Generate test coverage
        run: npm run test -- --coverage || true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella

  # Security scanning stage
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate || true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # Package stage
  package:
    name: Create Deployment Package
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}

      - name: Create deployment package
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          if [ "${{ github.ref_type }}" != "tag" ]; then
            VERSION="${{ github.sha }}"
          fi
          
          mkdir -p deploy-package
          cp -r apps/console/dist deploy-package/
          cp -r apps/console/src/ui deploy-package/ui
          cp apps/console/package.json deploy-package/
          echo "$VERSION" > deploy-package/VERSION
          
          tar -czf console-app-${VERSION}.tar.gz -C deploy-package .
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: console-app-${{ env.VERSION }}
          path: console-app-*.tar.gz
          retention-days: 90

      - name: Create npm packages
        run: npm pack --workspaces

      - name: Upload npm packages
        uses: actions/upload-artifact@v4
        with:
          name: npm-packages-${{ env.VERSION }}
          path: "*.tgz"
          retention-days: 90

  # Docker build stage (optional)
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aureus/console
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/console/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
